name: mallet-dev

services:
  frontend:
    environment:
      - NODE_ENV=development
      - PORT=3000
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - graphql
    volumes:
      - ./frontend/src/__generated__:/usr/src/frontend/src/__generated__
      # - ./frontend/dist:/usr/src/frontend/dist
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/frontend
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./frontend
          ignore:
            - node_modules/
            - dist/
            - src/
            - public/
            - README.md
            - .gitignore
            - .dockerignore
  graphql:
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:FYnHvLGqxxLWAkAWNexTcNuqUHDreRPq@db:5432/postgres
      - REDIS_PORT=6379
      - REDIS_HOST=cache
      - REDIS_PASSWORD=4RydQWxu42bfDMkmR97BuN8nfB6rVy52
    build: ./graphql
    container_name: graphql
    ports:
      - "4000:4000"
    depends_on:
      - db
      - cache
    volumes:
      - ./graphql/src/__generated__:/usr/src/graphql/src/__generated__
      # - ./graphql/dist:/usr/src/graphql/dist
    develop:
      watch:
        - action: sync+restart
          path: ./graphql
          target: /usr/src/graphql
          ignore:
            - node_modules/
            - dist/
            - src/__generated__/
            - .env
        - action: rebuild
          path: ./graphql/package.json
        - action: rebuild
          path: ./graphql/prisma/migrations
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FYnHvLGqxxLWAkAWNexTcNuqUHDreRPq
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 4RydQWxu42bfDMkmR97BuN8nfB6rVy52
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
